# Generated by Django 3.2.9 on 2022-11-13 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='events.imagealbum'),
        ),
    ]
