# Generated by Django 3.2.9 on 2022-12-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='length',
            new_name='distance',
        ),
        migrations.AddField(
            model_name='event',
            name='difficulty_level',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Сложность от 1 до 10'),
        ),
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Дистанция, км'),
        ),
    ]
