# Generated by Django 3.2.9 on 2022-10-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_planned',
            field=models.DateTimeField(),
        ),
    ]
