# Generated by Django 3.2.9 on 2022-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221207_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['album'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='imagealbum',
            options={'verbose_name': 'ФотоАльбом', 'verbose_name_plural': 'ФотоАльбомы'},
        ),
        migrations.RenameField(
            model_name='ip',
            old_name='date_edit',
            new_name='date_add',
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(default='ФотоАльбом', max_length=100),
        ),
    ]
