# Generated by Django 3.2.9 on 2022-10-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_date_planned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_planned'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
