# Generated by Django 3.2.9 on 2022-12-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20221214_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(blank=True, to='events.Ip', verbose_name='Просмотры'),
        ),
    ]
