# Generated by Django 3.2.9 on 2022-10-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20221020_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_planned',
            field=models.DateTimeField(),
        ),
    ]
