# Generated by Django 3.2.9 on 2022-12-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20221214_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
