# Generated by Django 3.2.9 on 2022-10-20 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_date_planned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='event_type',
        ),
    ]
