# Generated by Django 3.2.9 on 2022-10-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_article_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='text',
        ),
    ]
