# Generated by Django 3.2.9 on 2022-12-18 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20221215_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon_string', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Иконка ссылки',
                'verbose_name_plural': 'Иконки ссылок',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='events.linkicon', verbose_name='Иконка ссылки'),
        ),
    ]
