# Generated by Django 3.2.9 on 2022-10-18 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20221018_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название дорожного покрытия')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Уникальный слаг')),
            ],
            options={
                'verbose_name': 'Тип дорожного покрытия',
                'verbose_name_plural': 'Типы дорожных покрытий',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameField(
            model_name='article',
            old_name='caption',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='caption',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='caption',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='caption',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='caption',
            new_name='title',
        ),
        migrations.AddField(
            model_name='route',
            name='height_gain',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='surface_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='events.eventtype'),
        ),
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.ManyToManyField(related_name='routes', to='events.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='route',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
