# Generated by Django 3.2.9 on 2022-12-18 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20221218_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='events.event'),
        ),
    ]
