# Generated by Django 3.2.9 on 2022-10-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20221019_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='surface_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='events.surfacetype'),
        ),
    ]
