# Generated by Django 3.2.9 on 2022-10-21 23:23

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='gpx',
            field=models.FileField(blank=True, upload_to=events.models.user_directory_path),
        ),
    ]
