# Generated by Django 3.2.9 on 2022-12-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_report_report_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to='routes/images/', verbose_name='Скрин маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на внешний ресурс с треком (не обязательно)'),
        ),
    ]
