# Generated by Django 3.2.9 on 2022-10-19 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_route_surface_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тип маршрута',
                'verbose_name_plural': 'Типы маршрутов',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='events.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='route',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='routes', to='events.Tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='events.routetype'),
        ),
    ]
