# Generated by Django 3.2.9 on 2022-10-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_route_gpx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='text',
        ),
    ]
