# Generated by Django 3.2.9 on 2022-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20221220_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Порядковый номер'),
        ),
    ]
