# Generated by Django 3.2.9 on 2022-10-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_description_event_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
