# Generated by Django 3.2.9 on 2022-12-30 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0010_alter_link_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='to_tlg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Дата правки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created'],
            },
        ),
    ]
