# Generated by Django 3.2.9 on 2022-10-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_route_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
