# Generated by Django 3.2.9 on 2023-01-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20221230_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='to_tlg',
            field=models.BooleanField(default=False, verbose_name='Запостить в Телеграм'),
        ),
    ]
