# Generated by Django 3.2.9 on 2022-10-22 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_route_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surfacetype',
            options={'ordering': ['-id'], 'verbose_name': 'Тип маршрута', 'verbose_name_plural': 'Типы маршрутов'},
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='events.eventtype'),
        ),
        migrations.DeleteModel(
            name='RouteType',
        ),
    ]
