# Generated by Django 3.2.9 on 2022-10-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20221022_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surfacetype',
            options={'ordering': ['-id'], 'verbose_name': 'Тип дорожного покрытия', 'verbose_name_plural': 'Типы дорожных покрытий'},
        ),
    ]
