# Generated by Django 3.2.9 on 2022-10-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_surfacetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='polyline_field',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
