# Generated by Django 3.2.9 on 2022-10-22 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_route_polyline_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='polyline_field',
            new_name='polyline',
        ),
    ]
