# Generated by Django 3.2.9 on 2022-10-22 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_rename_polyline_field_route_polyline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='gpx',
            new_name='gpx_field',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='polyline',
            new_name='polyline_field',
        ),
    ]
