# Generated by Django 3.2.9 on 2022-10-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20221023_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='gpx_field',
            new_name='gpx',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='polyline_field',
            new_name='polyline',
        ),
    ]
