# Generated by Django 3.2.9 on 2022-10-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20221023_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='polyline',
            field=models.TextField(blank=True),
        ),
    ]
