# Generated by Django 3.2.9 on 2022-10-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='about',
            name='html_field',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='about',
            name='markdown_field',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
