# Generated by Django 3.2.9 on 2022-10-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20221024_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='height_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='routes', to='events.Tag', verbose_name='Теги'),
        ),
    ]
