# Generated by Django 3.2.9 on 2022-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20221029_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='height_gain',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
