# Generated by Django 3.2.9 on 2022-10-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20221029_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='gpx',
            new_name='track',
        ),
    ]
