# Generated by Django 3.2.9 on 2022-10-29 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0025_alter_route_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='route',
            name='height_gain',
            field=models.IntegerField(blank=True, default=0, verbose_name='Набор высоты, м'),
        ),
        migrations.AlterField(
            model_name='route',
            name='length',
            field=models.IntegerField(blank=True, default=0, verbose_name='Дистанция, км'),
        ),
        migrations.AlterField(
            model_name='route',
            name='surface_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='events.surfacetype', verbose_name='Покрытие'),
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='events.eventtype', verbose_name='Тип активности'),
        ),
    ]
