# Generated by Django 3.2.9 on 2022-10-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20221029_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='image',
            field=models.ImageField(blank=True, upload_to='routes/', verbose_name='Картинка'),
        ),
    ]
