# Generated by Django 3.2.9 on 2022-10-29 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0028_alter_route_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='route',
            name='polyline',
            field=models.TextField(blank=True, verbose_name='Полилиния (необязательно)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='route',
            name='track',
            field=models.FileField(blank=True, null=True, upload_to=events.models.user_directory_path, verbose_name='GPX-трек (если имеется)'),
        ),
        migrations.AlterField(
            model_name='route',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка (если есть)'),
        ),
    ]
