# Generated by Django 3.2.9 on 2022-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20221030_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='polyline',
            field=models.TextField(blank=True, editable=False, verbose_name='Полилиния (необязательно)'),
        ),
    ]
