# Generated by Django 3.2.9 on 2022-11-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20221104_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='articles_views', to='events.Ip'),
        ),
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='reports_views', to='events.Ip'),
        ),
        migrations.AddField(
            model_name='route',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='routes_views', to='events.Ip'),
        ),
    ]
