# Generated by Django 3.2.9 on 2022-11-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20221104_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['id'], 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
    ]
