# Generated by Django 3.2.9 on 2022-11-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_alter_link_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
