# Generated by Django 3.2.9 on 2022-11-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_alter_ip_date_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.ManyToManyField(blank=True, editable=False, related_name='events_views', to='events.Ip'),
        ),
    ]
