# Generated by Django 3.2.9 on 2022-11-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_event_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(blank=True, editable=False, related_name='articles_views', to='events.Ip'),
        ),
        migrations.AlterField(
            model_name='report',
            name='views',
            field=models.ManyToManyField(blank=True, editable=False, related_name='reports_views', to='events.Ip'),
        ),
        migrations.AlterField(
            model_name='route',
            name='views',
            field=models.ManyToManyField(blank=True, editable=False, related_name='routes_views', to='events.Ip'),
        ),
    ]
